### ISSUE TITLE
Docker Image - Run as nonRoot

### ISSUE THREAD

**Issue by just1689** [TwinProduction/gatus#105]
Good day

Hope everyone is well.

A good idea for various reasons would be to for the final Docker image to run as a non root user with a very high user ID / Group ID.

Happy to take a crack at it.

**Comment by TwinProduction** [comment]
I'm not sure it's possible; the [ICMP feature](https://github.com/TwinProduction/gatus#monitoring-a-service-using-icmp) requires elevated access.
That said, feel free to give it a try and see if you can get it working.

**Comment by pred2k** [comment]
i wanted to share my hardened `compose.yaml` which works well atm, because i only have HTTPS endpoint checks

```yaml
services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    user: 1000:1000
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ./config:/config
      - ./data:/data/
```

My `config/config.yaml` has a sqlite storage config. This is what i need `data/` for.
```yaml
storage:
  type: sqlite
  path: /data/data.db
```

I had to change the ownership of the folder/files before using the updated `compose.yaml`: 
```
chown -R 1000:1000 ./config/ ./data/
```

**Comment by SeaweedbrainCY** [comment]
For kubernetes, this is how I hardened the deployment 
```yaml
    spec:
      containers:
        - name: gatus
          image: "twinproduction/gatus:v5.35.0"
          securityContext:
            runAsNonRoot: true
            runAsUser: 2001
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_RAW"]
```

I do have ICMP endpoint, but the NET_RAW capability seems to be enough
