### ISSUE TITLE
Host Header Problem

### ISSUE THREAD

**Issue by windonis** [TwinProduction/gatus#114]
Hello Devs,

I found [this](https://github.com/TwinProduction/gatus/issues/60) issue but this feature still not working. 

Summary, I use curl like this;

```
➜  ~ curl https://160.75.25.12 -H "Host: itu.edu.tr" -Ik
HTTP/2 200
cache-control: no-cache
pragma: no-cache
content-length: 103421
content-type: text/html; charset=utf-8
expires: -1
server: Microsoft-IIS/10.0
x-aspnet-version: 4.0.30319
referrer-policy: no-referrer-when-downgrade
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-powered-by: ASP.NET
date: Mon, 17 May 2021 17:28:10 GMT
```
There is no problem for receiving 200 status code but when I use this configuration on `gatus`

```
services:
  - name: ITU
    url: https://160.75.25.12
    interval: 5s
    headers:
      Host: itu.edu.tr
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
```
`gatus` cannot get 200 status code. 

<img width="1342" alt="resim" src="https://user-images.githubusercontent.com/40137486/118531752-d98a8c80-b74e-11eb-89b3-014b593c34d6.png">

I dont know golang that is why I cannot fix this but I think the code you are testing the `host header` is wrong.

At this line ( [FUNC](https://github.com/TwinProduction/gatus/blob/67c3bf6e5ed1baa0a38d7f1f46fd30211e20b5c1/core/service_test.go#L162) ), you are using both url and header.

If you are using both of them, client dont use `Host` header. It performs DNS resolve and goes to the required IP address with the hostname in the url. That is why, the test is always successful.

Example;

```
➜  ~ curl https://itu.edu.tr -H "Host: google.com" -Ik
HTTP/2 200
cache-control: no-cache
pragma: no-cache
content-length: 103421
content-type: text/html; charset=utf-8
expires: -1
server: Microsoft-IIS/10.0
x-aspnet-version: 4.0.30319
referrer-policy: no-referrer-when-downgrade
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-powered-by: ASP.NET
date: Mon, 17 May 2021 17:36:58 GMT
```

Best Regards
Thank you for creating and keeping Gatus alive.

**Comment by windonis** [comment]
Hello,

When I try `http` does not problem.

But when I try with `https` stil problem although it's certificate is valid.

**Comment by TwinProduction** [comment]
Hello @windonis, it's probably because Gatus automatically checks the certificate, and because the certificate is not valid for an IP, but for a domain instead, when you query the IP directly, even though you have a `Host` header, the certificate check fails.

Would setting the `insecure` parameter to `true` be an option for you?
e.g.:
```yaml
services:
  - name: ITU
    url: https://160.75.25.12
    interval: 5s
    insecure: true      # <---------
    headers:
      Host: itu.edu.tr
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
```

**Comment by windonis** [comment]
Unfortunatelly, stil not working with `insecure` param. Can you test with this configuration 

<img width="1530" alt="resim" src="https://user-images.githubusercontent.com/40137486/118664606-49098600-b7fa-11eb-9bcd-f854e3819514.png">

```
services:
  - name: ITU
    url: https://160.75.25.12
    interval: 5s
    insecure: true
    headers:
      Host: itu.edu.tr
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
```
