### ISSUE TITLE
Support grouping services

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#13]
Supporting service groups could allow a cuter front end experience.

i.e.
```yaml
services:
  - name: k8s-cluster-watch-dog
    url: http://k8s-cluster-watch-dog-v1.tools-${ENVIRONMENT}:8080/health
    group: core         <-------
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
  - name: prometheus
    url: http://prometheus-operator-prometheus.kube-system:9090/-/healthy
    group: core         <-------
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == Prometheus is Healthy."
```

would generate a dashboard that puts both `k8s-cluster-watch-dog` and `prometheus` under the "core" folder.

![image](https://user-images.githubusercontent.com/15699766/93811861-c7d40200-fc1e-11ea-8fe7-6747616f1993.png)

Could also support tags, and allow filtering by tags instead

i.e.
```yaml
services:
  - name: k8s-cluster-watch-dog
    url: http://k8s-cluster-watch-dog-v1.tools-${ENVIRONMENT}:8080/health
    tags:              <-------
      - core
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"
  - name: prometheus
    url: http://prometheus-operator-prometheus.kube-system:9090/-/healthy
    tags:              <-------
      - core
      - metrics
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == Prometheus is Healthy."
```

![image](https://user-images.githubusercontent.com/15699766/93812350-74ae7f00-fc1f-11ea-9ca0-7ce12f0f634c.png)

Forgive the terrible drafts, just thought of this on the fly.
