### ISSUE TITLE
More alert customization

### ISSUE THREAD

**Issue by derekoharrow** [TwinProduction/gatus#130]
I'm using custom alerts to have Gatus alert via Pushover.

However, I'd really like the ability to have different alert configurations for pushover (i.e. multiple custom alerts).

The reason for this is that to get Pushover working, I have to embed the Pushover API parameters in the custom alert body, and I'd really like to be able to have more than one config for pushover - e.g. normal priority and high priority. I can't do this as I can only have one custom alert definition, and you cannot override the custom alert body text from within the service definition.

To get around this you could either:
1. Enable multiple custom alerts (or multiple alert definitions of any type for that matter) - giving them a name (e.g. custom1, slack2, etc) and then defining the alert characteristics.

```
alerting:
  custom:
    name: custom1                     <<<<<<<<<<<<
    url: "https://hooks.slack.com/services/**********/**********/**********"
    method: "POST"
    insecure: true
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME] - [ALERT_DESCRIPTION]"
      }
services:
  - name: twinnation
    url: "https://twinnation.org/health"
    interval: 30s
    alerts:
      - type: custom1                     <<<<<<<<<<<<
        enabled: true
        failure-threshold: 10
        success-threshold: 3
        send-on-resolved: true
        description: "healthcheck failed"
```

2. Enable all fields of the alert to be overridden within the service definition - e.g. being able to override the body text, etc.
alerting, e.g.
```
  custom:
    url: "https://hooks.slack.com/services/**********/**********/**********"
    method: "POST"
    insecure: true
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME] - [ALERT_DESCRIPTION]"
      }
services:
  - name: twinnation
    url: "https://twinnation.org/health"
    interval: 30s
    alerts:
      - type: custom
        enabled: true
        body: { ALTERNATE BODY TEXT HERE }                     <<<<<<<<<<<<
        failure-threshold: 10
        description: "healthcheck failed"
```
