### ISSUE TITLE
ICMP does not work on Mac OS

### ISSUE THREAD

**Issue by xoraingroup** [TwinProduction/gatus#132]
MAC OS Big Sur version 11.0.1

Everything works perfectly ok except icmp in MAC OS.

Config:

  - name: node-1
    url: "icmp://104.237.x.x"
    group: Uptime (Ping)
    conditions: 
      - "[CONNECTED] == true"
      - "[RESPONSE_TIME] > 0"

![image](https://user-images.githubusercontent.com/17129052/125159622-34ee5f00-e181-11eb-90f9-d3d53ac287ed.png)

the x.x is in ip is set intentionally. 

Is this wrong config?

**Comment by TwinProduction** [comment]
I assume that the `x.x` is there to hide your IP -- can you try the following instead:
```yaml
  - name: node-1
    group: Uptime (Ping)
    url: "icmp://127.0.0.1"
    conditions:
      - "[CONNECTED] == true"
      - "[RESPONSE_TIME] < 150"
```
