### ISSUE TITLE
Allow multiple checks per service

### ISSUE THREAD

**Issue by tiwood** [TwinProduction/gatus#149]
It would be nice if we could configure multiple checks per service, something like this:

```yaml
- name: DNS lookup
  checks:
    # Check if we can resolve www.google.com
    - url: "10.10.10.10"
      interval: 1m  
      dns:
        query-name: "www.google.com"
        query-type: "A"
      conditions:
        - "[DNS_RCODE] == NOERROR"

    # Check if we can resolve www.google.de
    - url: "10.10.10.10"
      interval: 1m  
      dns:
        query-name: "www.google.de"
        query-type: "A"
      conditions:
        - "[DNS_RCODE] == NOERROR"
```

Maybe we could also define if the service is `degraded` or `down` if one of the checks fails, like so:

```yaml
- name: DNS lookup
  checks:
    # Check if we can resolve www.google.com
    - url: "10.10.10.10"
      interval: 1m  
      dns:
        query-name: "www.google.com"
        query-type: "A"
      conditions:
        - "[DNS_RCODE] == NOERROR"
      service-impact: critical #could be one of "critical", "noncritical"  

    # Check if we can resolve www.google.de
    - url: "10.10.10.10"
      interval: 1m  
      dns:
        query-name: "www.google.de"
        query-type: "A"
      conditions:
        - "[DNS_RCODE] == NOERROR"
      service-impact: critical #could be one of "critical", "noncritical" 
```

`non-critical` Impacts could be shown with a `yellow` status box.
