### ISSUE TITLE
Ability to hide URL

### ISSUE THREAD

**Issue by erviker** [TwinProduction/gatus#159]
We use internal urls for some of the services and makes the url part redundant
![image](https://user-images.githubusercontent.com/482155/130296790-47ae4d78-4857-4527-9dd8-2cf863e6b0fe.png)

```
service:
        - name: favorite-svc
          url: tcp://favorite-svc:80
          hideurl: true
```

**Comment by TwinProduction** [comment]
Good idea, and even for privacy purposes, this could come in handy.

Here's how I think it should be reflected in the configuration, though:
```yaml
service:
  - name: favorite-svc
    url: tcp://favorite-svc:80
    ui:
      hide-url: true
```
I think putting it underneath `ui` is a better idea, because it'll blend in well with #106, or more specifically, what I suggested in https://github.com/TwinProduction/gatus/issues/106#issuecomment-907715856
