### ISSUE TITLE
Self-signed certificate checking error: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by rtzra** [TwinProduction/gatus#164]
Self-signed certificate checking error, get message: "x509: certificate signed by unknown authority"
I try client.insecure=true, but still no effect.
![gatus-cert](https://user-images.githubusercontent.com/2812450/131641262-11525321-755e-40c6-83bd-8c7606c3a5cf.png)

My config:
- name: Grafana
      url: "https://grafana.gk.x5.ru"
      group: "02 Grafana"
      client:
        insecure: true
        ignore-redirect: true
        timeout: 5s
      interval: 30s
      conditions:
        - "[STATUS] == 200"
        - "[RESPONSE_TIME] < 50"

**Comment by rtzra** [comment]
Sorry, i use old version 2.7.0, but client.insecure=true work only from 2.8.x

**Comment by Graxo** [comment]
Is there documentation about this?

**Comment by luckylinux** [comment]
@Graxo: https://github.com/TwiN/gatus?tab=readme-ov-file#client-configuration

Adding the following under a `<endpoint>` Entry allows to skip the TLS Certificate Verification:
```
client:
  insecure: true
```

So the entire entry becomes:
```
endpoints:
  - name: MY_HOST
    group: MY_GROUP
    url: "https://MY_HOST.MYDOMAIN.TLD/"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
```
