### ISSUE TITLE
docker gatus on Linux host - ICMP tests failing

### ISSUE THREAD

**Issue by waywardone** [TwinProduction/gatus#182]
I'm using gatus in a docker container on a Linux host and find that all icmp tests fail - even for hosts that are up and reachable via ICMP. Other tests like TCP and HTTP work as expected. I noticed the changes related to pinger.SetPrivileged and have picked up the most recent image available but ICMP tests still fail. Here's my docker-compose:

```
   gatus:
     container_name: gatus
     hostname: gatus
     restart: unless-stopped
     image: twinproduction/gatus:latest
     ports:
       - 4008:8080
     volumes:
       - ${USERDIR}/docker/gatus/data:/data
       - ${USERDIR}/docker/gatus/config.yaml:/config/config.yaml
     environment:
         TZ: "${TZ}"
```

and here's an example configuration for icmp that fails (when it should not):
```
   - name: huginn
     group: my-network
     url: "icmp://google.com"
     interval: 1m
     conditions:
       - "[CONNECTED] == true"
```

![gatus-icmp-test](https://user-images.githubusercontent.com/1276353/136312688-08bedb2a-cb0e-4d04-a81f-b20da7422348.png)

A log entry for the test:

```
2021/10/07 02:53:15 [watchdog][execute] Monitored group=my-network; service=google; success=false; errors=0; duration=0s
```

Other things I've tried without any difference in behavior:
* used IP addresses instead of names
* configured ICMP test for 127.0.0.1
