### ISSUE TITLE
Support alerting

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#2]
Support alerting via Slack webhook and/or PagerDuty

```yaml
alert:
  slack: "http://...."
  pagerduty: "http://...."

services:
  - name: example
    url: https://example.org/
    interval: 30s
    alerts:
      - type: slack
        enabled: true
        threshold: 5
        description: "Request failed 5 times in a row"
      - type: pagerduty
        enabled: true
        threshold: 10
        description: "Request failed 10 times in a row"
    conditions:
      - "[STATUS] == 200"
```

Would trigger a Slack alert after 5 failures in a row and a PagerDuty alert after 10 failures in a row.

### Notes

Could store the number of failures in a row in the service rather than in the result, that way there would be no need to store more than 20 results per service. Might also help prevent triggering the same alerts twice?
