### ISSUE TITLE
Add placeholder to resolve time left until certificate expiration

### ISSUE THREAD

**Issue by r3vit** [TwinProduction/gatus#28]
Hi!

Actually I'm using a service called "Uptime Robot" that offers this check: if a certificate is going to expire in X days, it sends me a message on slack or an email.

This can probably be a new condition [CERTIFICATE] or [CERT_EXPIRE] or [CERTIFICATE_EXPIRE] like:

```
metrics: true         # Whether to expose metrics at /metrics
services:
  - name: twinnation  # Name of your service, can be anything
    url: "https://twinnation.org/health"
    interval: 30s     # Duration to wait between every status check (default: 60s)
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[BODY].status == UP"     # The json path "$.status" must be equal to UP
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms
      - "[CERTIFICATE_EXPIRE] > 1week"   # Certificate must expire in more than a week
  - name: example
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
```

The check can be done with standard go library or something like `github.com/genkiroid/cert`. This summer i worker on a custom go program similar to Gatus written with this library:
```
// Load the certificate from the host.
certificate := cert.NewCert(domain.Host)
// Check if it's expiring in less than 1 month.
		if certificate.Detail().NotAfter.Before(time.Now().AddDate(0, 1, 0)) { 
		.....
```

I leave here the feature proposal. I know that is not exactly a thing that is useful to check every 30seconds, but in my specific use case it will be really useful if this can be tested day by day or something similar.

Anyway, thank you for Gatus! It's a really good self-hosted solution for this type of monitoring.
