### ISSUE TITLE
Support header conditions

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#4]
Gatus should provide a way to add conditions to validate the value of a header.

Here's what it could look like:
```yaml
  - name: example
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "[HEADER][Content-Encoding] == gzip"
```

Note that thanks to RFC 2616, headers must be case insensitive.

**Comment by MaartenW** [comment]
Logical follow up would be to check `[HEADER][last-modified]` for age

**Comment by Carlotronics** [comment]
Hi @TwinProduction, I created #178 but I hesitate on how to handle multi-values header. I think adding an operator, such as `<in>` would make sense. It would lead to following configuration:

```yaml
  - name: example
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "gzip <in> [HEADER].Content-Encoding"
```

User could choose to keep current behavior (only first value is considered) by using the configuration you wrote in your initial post.
