### ISSUE TITLE
Add Discord as an alerting provider

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#48]
It's currently possible to use Discord as an alerting provider by using the `custom` configuration:

```yaml
alerting:
  custom:
    url: "https://discord.com/api/webhooks/******/*********/slack"
    method: "POST"
    body: |
      {
        "text": ":helmet_with_cross: **Gatus**\nAn alert for **[SERVICE_NAME]** has been **[ALERT_TRIGGERED_OR_RESOLVED]**\n> [ALERT_DESCRIPTION]"
      }
```

The result from the custom alert above looks like this:

---

⛑️ **Gatus**
An alert for **example** has been **TRIGGERED**
> wow

---

While this works, custom alerts don't currently support placeholders for individual conditions, which is why non-custom providers are necessary for sending visually pleasant notifications:
![Slack Gatus notifications](https://user-images.githubusercontent.com/15699766/99883565-5bfa1f80-2bf6-11eb-868f-d29779339348.png)

This issue is for implementing notifications similar to that of Slack, but for Discord.
The provider configuration should look like so:
```yaml
alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/******/*********"
```

The easiest way to implement this feature would be to:
- Automatically append `/slack` to the end of `alerting.discord.webhook-url`
- Create an AlertProvider similar to that of Slack, but the request body should only be `{ "text": "..." }` rather than `slack.AlertProvider`'s more complex request body, as it doesn't seem to work with Discord's webhook.

I'm planning on implementing this soon, but if somebody else would like to give it a try before I do, feel free to let me know.
