### ISSUE TITLE
Support random body variables

### ISSUE THREAD

**Issue by MaartenW** [TwinProduction/gatus#56]
Gatus could support dynamic POST body variables.
To enable checking the functionality of API's.

It could look like this:
```
 - name: "test variables"
    url: "https://api.example.com/v1/orders"
    method: POST
    body: { "amount" : [RAND(1,10)]}
    conditions:
        - "[BODY].orders.amount == [LAST_RAND]"
```
