### ISSUE TITLE
Retry request in case of failure

### ISSUE THREAD

**Issue by GeorgFleig** [TwinProduction/gatus#59]
It would be great if Gatus had the possibility to retry a failed request `X` times with `Y` interval to verify an endpoint is "really" down and it is not just a short hiccup.

I saw this is already implemented for alerts (`services[].alerts[].failure-threshold`), but with this setting it will be shown as down on the dashboard anyway. And the interval for the retry is the same.

I was thinking of something like this:
```
  - name: google
    url: "https://google.com"
    interval: 1m
    retry-count: 2
    retry-interval: 10s
    conditions:
      - "[STATUS] == 200"
```
In case `retry-interval` is not set, `interval` is used. Not sure if it makes sense though to have the alert failure threshold and a generic retry logic.
