### ISSUE TITLE
Config in env variables is weak

### ISSUE THREAD

**Issue by pollosp** [TwinProduction/gatus#75]
First of all nice work with Gatus folks 👏 , thank for the effort here and doing it opensource.

When I was setting up Gatus and I missed the availability of write some config as ENV variable , I thought it could be nice  specially for the alerting configuration with secrets tokens and private urls. 
Using environment variables way maybe you can use the config yml file as template or base for multiple environments and set those settings independently of the environment. 

I'm thinking in a scenario where some config is populated to a container using ENV variables like with ECS + [Chamber](https://github.com/segmentio/chamber) or ECS + [ssm-env](https://github.com/remind101/ssm-env) overriding or complementing the yml file. 

For example you are doing it with `GATUS_CONFIG_FILE` which is very useful if you maintain and build those yml files , per environment

Is something like this in your roadmap? Do you think this could be useful?
Thanks again.

**Comment by TwinProduction** [comment]
@pollosp In fact, you can use environment variables in your configuration.

For instance:
```yaml
services:
  - name: twinnation
    url: "http://${ENVIRONMENT}.example.org/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
```

If you want to use environment variables in your alerting configuration, you could do the following:
```yaml
alerting:
  slack: 
    webhook-url: "${SLACK_WEBHOOK_URL}"
```
