### ISSUE TITLE
Subscription management.

### ISSUE THREAD

**Issue by AndreiPaulau** [TwinProduction/gatus#84]
That might look as an old fashioned, but still can be effective.
I would expect that someone knowing that the list of endpoints mentioned in gatus dashboard is really big.
The person would like to know the service health of several services from the list, let's say 3/20.
Would be great if a person could subscribed to these 3 required endpoints and would get let's say emails over failure and recovery.

**Comment by TwinProduction** [comment]
By "person", do you mean any visitors that can access the dashboard (UI), or do you mean a developer that has access to Gatus' configuration and can modify/redeploy it?

If it's the latter, technically, it would be possible to do it if an alerting provider for emails was implemented. 
For instance, you could configure it so if a service failed more than 3 times in a row, an email would be sent to a given email address.

**Comment by AndreiPaulau** [comment]
By person I mean visitor/end-user.
I'm already configured slack alerting.
My case is:
We've configured a bunch of corp endpoints to track.
Some of them are point of interest for sales, some for managers some for devs.
For now everything is alerting to a single slack channel.
Thus there is a situation, "Oh! Alert, ughhh, not mine service" =)
So in case if visitor would have an option to subscribe to set of specific groups/services, he would avoid such situation.
If Devs are happy with slack IMHO sales/managers are happy about emails still these days=)

BTW, gatus is super cool! Thanks for your work! =)

**Comment by TwinProduction** [comment]
An immediate solution I can think of is to create a user group for each groups of relevant group of employees , and in the alert description, ping the relevant group.

For instance:
```yaml
alerting:
  slack: 
    webhook-url: "https://hooks.slack.com/services/**********/**********/**********"

services:
  - name: relevant-to-managers
    url: "https://example-for-managers.org/"
    alerts:
      - type: slack
        enabled: true
        description: "<@!subteam^SLACK_MANAGER_GROUP_ID>"
    conditions:
      - "[STATUS] == 200"

  - name: relevant-to-devs
    url: "https://example-for-devs.org/"
    alerts:
      - type: slack
        enabled: true
        description: "<!subteam^SLACK_DEV_GROUP_ID>"
    conditions:
      - "[STATUS] == 200"
```
(note the `services[].alerts[].description`, [reference](https://api.slack.com/reference/surfaces/formatting#mentioning-groups))

That way, by tweaking the notification settings, each groups could be notified only when it concerns them.

That being said, I do understand that this is more of a hack than a viable solution; I think the root cause is that there may be a need for supporting multiple slack webhooks rather than just one, even if you could technically use `custom` to create a 2nd Slack provider, having the ability to create N alerting providers would be better.

Across all alerting providers, there appears to always only one parameter that may need to change in order to support multiple recipients:
- **Slack**: webhook-url
- **PagerDuty**: integration-key
- **Twilio**: to
- **Mattermost**: recipients
- **Custom**: URL, but probably irrelevant 

As a result, we may be able to just add a single optional parameter to the service alert (as opposed to the alerting provider) to override that "key" parameter for a specific service:

```yaml
alerting:
  slack: 
    webhook-url: "https://hooks.slack.com/services/**********/**********/webhook-for-managers"

services:
  - name: relevant-to-managers
    url: "https://example-for-managers.org/"
    alerts:
      - type: slack
        enabled: true
    conditions:
      - "[STATUS] == 200"

  - name: relevant-to-devs
    url: "https://example-for-devs.org/"
    alerts:
      - type: slack
        enabled: true
        override-target: "https://hooks.slack.com/services/**********/**********/webhook-for-devs"
    conditions:
      - "[STATUS] == 200"
```

As a result, the `relevant-to-devs` service would send to the overridden webhook `https://hooks.slack.com/services/**********/**********/webhook-for-devs` instead of the default `"https://hooks.slack.com/services/**********/**********/webhook-for-managers"`.

It's a little hacky, especially when you look at the Slack alerting provider which only has a single parameter (`webhook-url`) as opposed to the Twilio alerting provider, which has several parameters out of which only one is relevant to alert a different target (`to`), but I think that if we want to avoid breaking changes, this is the best way to do it: it's transparent for those that don't need the feature, and while most users will likely never use that feature, the option is still available.
