### ISSUE TITLE
Notifications when service is up again

### ISSUE THREAD

**Issue by guillomep** [TwinProduction/gatus#9]
It would be great if we can add an alert when the service is up again.
We used it to monitor our kubernetes services and so it can be down for a time then up again without any actions, so if we can be inform that the service is up again it's great.

Something like that could be used

```
alerts:
      - type: slack
        enabled: true
        description: "healthcheck failed 3 times in a row"
        upAlert: true
```
